# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  specialoffers:
    image: specialoffers
    build:
      context: .
      dockerfile: SpecialOffers/Dockerfile
    ports:
      - 5000:80
  notifications:
    image: notifications
    build:
      context: .
      dockerfile: Notifications/Dockerfile
    ports:
      - 5001:80

